package app.registrationSystem.security;

public enum Privilege {
    ADD_DOCTOR, ADD_ADMIN, REMOVE_ADMIN, REMOVE_DOCTOR, REMOVE_NURSE, REMOVE_PATIENT,
    CHANGE_CREDENTIALS, ADD_ILLNESS, CHECK_DOCTORS, CHECK_SPECIALIZATIONS, ADD_VISIT, CHECK_AVAILABLE_VISITS,
    SCHEDULE_VISIT, CHECK_SCHEDULED_VISITS, CHECK_ASSIGNED_ILLNESSES, PRESCRIBE_MEDICATIONS, CHECK_PRESCRIPTIONS, ADD_MEDICATIONS,
    CHECK_MEDICATIONS, ASK_QUESTION, ANSWER_QUESTION, REVIEW_VISIT, CHECK_REVIEWS, VERIFY_ACCOUNT, ENABLE_AVAILABLE_VISIT_NOTIFICATION,
    CHECK_CREDENTIALS, CHECK_VISIT_HISTORY

}
