package app.registrationSystem.security;

import java.util.Set;
import static app.registrationSystem.security.Privilege.*;

public enum Role {
    ADMIN(Set.of(ADD_ADMIN, ADD_DOCTOR, REMOVE_ADMIN, REMOVE_NURSE, REMOVE_DOCTOR, REMOVE_PATIENT,
            CHECK_DOCTORS, CHECK_SPECIALIZATIONS, ADD_MEDICATIONS, CHECK_REVIEWS, VERIFY_ACCOUNT)),
    DOCTOR(Set.of(CHANGE_CREDENTIALS, CHECK_DOCTORS, CHECK_SPECIALIZATIONS, ADD_VISIT, CHECK_AVAILABLE_VISITS, CHECK_SCHEDULED_VISITS,
            PRESCRIBE_MEDICATIONS, CHECK_MEDICATIONS, CHECK_PRESCRIPTIONS, ANSWER_QUESTION, CHECK_REVIEWS, VERIFY_ACCOUNT)),
    PATIENT(Set.of(CHANGE_CREDENTIALS, ADD_ILLNESS, CHECK_DOCTORS, CHECK_SPECIALIZATIONS, CHECK_AVAILABLE_VISITS,
            SCHEDULE_VISIT, CHECK_SCHEDULED_VISITS, CHECK_ASSIGNED_ILLNESSES, CHECK_PRESCRIPTIONS, ASK_QUESTION,
            REVIEW_VISIT, CHECK_REVIEWS, VERIFY_ACCOUNT, ENABLE_AVAILABLE_VISIT_NOTIFICATION));

    final Set<Privilege> privileges;
    Role(Set<Privilege> privileges) {
        this.privileges = privileges;
    }

    Set<Privilege> getPrivileges() {
        return privileges;
    }
}
